const { Game } = require('../models');

const gameData = [
  {
    game_name: 'The Legend of Zelda: Breath of the Wild',
    price: 59.99,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: 'Super Mario Odyssey',
    price: 59.99,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: 'Animal Crossing: New Horizons',
    price: 55.99,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: 'Mario Kart 8 Deluxe',
    price: 59.99,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: 'Fire Emblem: Three Houses',
    price: 52.93,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: 'Tetris 99',
    price: 14.99,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: 'Pokemon Sword and Shield',
    price: 59.95,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: 'Super Smash Bros. Ultimate',
    price: 14.99,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: "Luigi's Mansion 3",
    price: 14.99,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: "Legend of Zelda: Link's Awakening",
    price: 14.99,
    stock: 14,
    console_id: [5, 6],
    category_id: 3,
  },
  {
    game_name: "Assassin's Creed Valhalla",
    price: 59.99,
    stock: 25,
    console_id: [3, 4],
    category_id: 3,
  },
  {
    game_name: "Astro's Playroom",
    price: 90.0,
    stock: 25,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: 'Call of Duty: Black Ops Cold War',
    price: 69.99,
    stock: 25,
    console_id: [3, 4],
    category_id: 3,
  },
  {
    game_name: "No Man's Sky",
    price: 59.99,
    stock: 25,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: 'Destiny 2',
    price: 0.00,
    stock: 25,
    console_id: [3, 4],
    category_id: 3,
  },
  {
    game_name: 'Devil May Cry 5 Special Edition',
    price: 90.0,
    stock: 25,
    console_id: [3, 4],
    category_id: 3,
  },
  {
    game_name: 'Dirt 5',
    price: 90.0,
    stock: 25,
    console_id: [3, 4],
    category_id: 3,
  },
  {
    game_name: 'NBA 2K21',
    price: 90.0,
    stock: 25,
    console_id: [3, 4],
    category_id: 3,
  },
  {
    game_name: 'Spider-Man: Miles Morales',
    price: 90.0,
    stock: 25,
    console_id: [3, 4],
    category_id: 3,
  },
  {
    game_name: 'Watch Dogs: Legion',
    price: 90.0,
    stock: 25,
    console_id: [3, 4],
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 22.99,
    stock: 12,
    console_id: 3,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 12.99,
    stock: 50,
    console_id: 4,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 5,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
  {
    game_name: '',
    price: 29.99,
    stock: 22,
    console_id: 6,
    category_id: 3,
  },
];

const seedGames = () => Game.bulkCreate(gameData);

module.exports = seedGames;
